name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: rudrikasharma15
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake to Output Branch
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: "Generate Snake Animation"
          add: "dist/github-contribution-grid-snake.svg"
